### PR TITLE
added new info

### PR DESCRIPTION
**Pull request by mariiaprokopieva**

### CODE REVIEW

**Review by AwaKareem00 — APPROVED** [review]
good

**Review by haiderDhari — COMMENTED** [review]
reviewed

**Review by AlinaHegyi — COMMENTED** [review]
great

**Review by YousefAlselwadi — COMMENTED** [review]
good

**Review by JibrilMusleh — COMMENTED** [review]
good

**Comment by YousefAlselwadi** [comment]
good

**Pull request closed without merging**
